# Generated by Django 3.2.6 on 2021-08-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='family',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='name',
        ),
    ]
