# Generated by Django 3.2.6 on 2021-08-05 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsales', '0002_auto_20210804_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=100)),
                ('profileimage', models.ImageField(null=True, upload_to='profileImages/')),
                ('gender', models.IntegerField(choices=[('man', 'مرد'), ('woman', 'زن')])),
            ],
        ),
        migrations.AddField(
            model_name='concertmodel',
            name='poster',
            field=models.ImageField(null=True, upload_to='concertImages/'),
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketimage', models.ImageField(null=True, upload_to='ticketImages/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('profilemodel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.profilemodel')),
                ('timemodel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.timemodel')),
            ],
        ),
    ]
