# Generated by Django 3.2.6 on 2021-08-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsales', '0003_auto_20210805_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertmodel',
            options={'verbose_name': 'کنسرت', 'verbose_name_plural': 'کنسرت'},
        ),
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'verbose_name': 'محل برگزاری', 'verbose_name_plural': 'محل برگزاری'},
        ),
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
        migrations.AlterModelOptions(
            name='ticketmodel',
            options={'verbose_name': 'بلیط', 'verbose_name_plural': 'بلیط'},
        ),
        migrations.AlterModelOptions(
            name='timemodel',
            options={'verbose_name': 'سانس', 'verbose_name_plural': 'سانس'},
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='length',
            field=models.IntegerField(verbose_name='طول کنسرت'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام کنسرت'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='poster',
            field=models.ImageField(null=True, upload_to='concertImages/', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='singername',
            field=models.CharField(max_length=100, verbose_name='نام خواننده'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='address',
            field=models.CharField(default='تهران شهرک غرب', max_length=500, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='capacity',
            field=models.IntegerField(verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام محل'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='family',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='gender',
            field=models.IntegerField(choices=[('man', 'مرد'), ('woman', 'زن')], verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='profileimage',
            field=models.ImageField(null=True, upload_to='profileImages/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='price',
            field=models.IntegerField(verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='profilemodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.profilemodel', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticketimage',
            field=models.ImageField(null=True, upload_to='ticketImages/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='timemodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.timemodel', verbose_name='سانس'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='concertModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.concertmodel', verbose_name='کنسرت'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='locationModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.locationmodel', verbose_name='محل برگزاری'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='seats',
            field=models.IntegerField(verbose_name='تعداد صندلی ها'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='startdatetime',
            field=models.DateTimeField(verbose_name='تاریخ و زمان برگزاری'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='status',
            field=models.CharField(choices=[('start', 'فروش بلیط شروع شده'), ('end', 'قروش بلیط تمام شده'), ('cancel', 'این سانس کنسل شده است'), ('sales', 'در حال فروش بلیط')], max_length=100, verbose_name='وضعیت'),
        ),
    ]
