# Generated by Django 3.2.6 on 2021-08-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsales', '0004_auto_20210812_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='gender',
            field=models.CharField(choices=[('man', 'مرد'), ('woman', 'زن')], max_length=50, verbose_name='جنسیت'),
        ),
    ]
