# Generated by Django 3.2.6 on 2021-08-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ticketsales', '0006_alter_timemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='profilemodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profilemodel', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='status',
            field=models.IntegerField(choices=[('start', 'فروش بلیط شروع شده'), ('end', 'فروش بلیط تمام شده'), ('cancel', 'این سانس کنسل شده است'), ('sales', 'در حال فروش بلیط')], verbose_name='وضعیت'),
        ),
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
